version: "3.9"
services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    networks:
      - mynetwork
networks:
  mynetwork: